name: f3rd
version: 1.08
author: f3rd
main: com.github.fate0608.StopIt.StopIt
commands:
  stopit:
    description: /stopit Delay Reason
  servername:
    messages:
      servername: JMC
  ts3ip:
    messages:
      ts3ip: ip